
spring:
  application:
    name: gateway-api
  config:
    import: "optional:configserver:http://localhost:8088 "

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
#
#        - id: order-service-order
#          uri: lb://order-service
#          predicates:
#            - Path=/api/v1/order/**
#          filters:
#            - AuthenticationFilter
#
#        - id: order-service-cart
#          uri: lb://order-service
#          predicates:
#            - Path=/api/v1/cart-items/**
#          filters:
#            - AuthenticationFilter
#
#        - id: product-service-seller
#          uri: lb://product-service
#          predicates:
#            - Path=/api/v1/seller/**
#          filters:
#            - AuthenticationFilter
#
#        - id: notification-service
#          uri: lb://notification-service
#          predicates:
#            - Path=/api/v1/notification/**
#          filters:
#            - AuthenticationFilter
#
#        - id: notification-service-socket
#          uri: lb://notification-service
#          predicates:
#            - Path=/ws/**
        #          filters:
        #            - AuthenticationFilter
#        - id: product-service
#          uri: lb://product-service
#          predicates:
#            - Path=/api/v1/**
        #          filters:
        #            - AuthenticationFilter

        #        - id: message-service
        #          uri: lb://message-service
        #          predicates:
        #            - Path=/
        #          filters:
        #            - AuthenticationFilter

#        - id: python-service
#          uri: lb://python-service
#          predicates:
#            - Path=/**
#          filters:
#            - AuthenticationFilter


