server:
  port: 9898

spring:
  application:
    name: gateway-api
  config:
    import: "optional:configserver:http://config-service:8088"

  cloud:
    gateway:
      routes:
#        - id: authentication-service
#          uri: lb://authentication-service
#          predicates:
#            - Path=/api/v1/users/**
#
#        - id: order-service-order
#          uri: lb://order-service
#          predicates:
#            - Path=/api/v1/order/**
#          filters:
#            - AuthenticationFilter
#
#        - id: order-service-cart
#          uri: lb://order-service
#          predicates:
#            - Path=/api/v1/cart-items/**
#          filters:
#            - AuthenticationFilter
#
#        - id: product-service-seller
#          uri: lb://product-service
#          predicates:
#            - Path=/api/v1/seller/**
#          filters:
#            - AuthenticationFilter
#
#        - id: notification-service
#          uri: lb://notification-service
#          predicates:
#            - Path=/api/v1/notification/**
#          filters:
#            - AuthenticationFilter
#
#        - id: notification-service-socket
#          uri: lb://notification-service
#          predicates:
#            - Path=/ws/**
        #          filters:
        #            - AuthenticationFilter
#        - id: product-service
#          uri: lb://product-service
#          predicates:
#            - Path=/api/v1/**
        #          filters:
        #            - AuthenticationFilter

        #        - id: message-service
        #          uri: lb://message-service
        #          predicates:
        #            - Path=/
        #          filters:
        #            - AuthenticationFilter

#        - id: python-service
#          uri: lb://python-service
#          predicates:
#            - Path=/**
#          filters:
#            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/
